package com.arraylist;

import java.util.Scanner;
import java.util.*;
public class Student_management {

	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		ArrayList<Integer> stud_id=new ArrayList<Integer>();
		ArrayList<Integer> stud_age=new ArrayList<Integer>();
		ArrayList<String> stud_name=new ArrayList<String>();
		ArrayList<Float> marks=new ArrayList<Float>();
		marks.add((float) 0.0);
		marks.add((float) 0.0);
		marks.add((float) 0.0);
		String batch="MCA";
		System.out.print("Enter how many student details you want to store:");
		int n=sc.nextInt();
		for(int i=0;i<n;i++)
		{
			sc.nextLine();
			System.out.print("Enter student Name:");
			String name=sc.nextLine();
			stud_name.add(name);
			try {
			System.out.print("Enter student Id:");
			int id=sc.nextInt();
			stud_id.add(id);
			
			System.out.print("Enter student age:");
			int age=sc.nextInt();
			stud_age.add(age);
			}
			catch(Exception e){
				System.out.println("Enter valid details");
			}
		}
		System.out.println("If you are a student then enter your id:");
		int ask_id=sc.nextInt();
		for(int i=0;i<n;i++)
		{
			   if(ask_id==stud_id.get(i))
			    {
				System.out.println("your name is "+stud_name.get(i));
				System.out.println("your id is "+stud_id.get(i));
				System.out.println("your age is "+stud_age.get(i));
				System.out.println("your marks is "+marks.get(i)+" which is not generated by teacher");
				break;
			    }
			   else if(ask_id!=stud_id.get(1)) 
			   {
					System.out.println("you are a new student & provide your details:");
					sc.nextLine();
					System.out.print("Enter your name:");
					String new_stud_name=sc.nextLine();
					stud_name.add(new_stud_name);
					System.out.print("Enter your id:");
					int new_stud_id=sc.nextInt();
					stud_id.add(new_stud_id);
					System.out.print("Enter your age:");
					int new_stud_age=sc.nextInt();
					stud_age.add(new_stud_age);
					break;
				   }
			continue;
	    }
		ArrayList<String> teachers=new ArrayList<String>();
		teachers.add("subasish");teachers.add("deepak");teachers.add("mehnaz");
		sc.nextLine();
		System.out.print("If you are a teacher then Enter your name:");
		String teach_name=sc.nextLine();
		for(int i=0;i<teachers.size();i++)
		{
		if(teach_name.equals(teachers.get(i)) )//|| teach_name==teachers.get(1) || teach_name==teachers.get(2))
		{
			System.out.println("yes you are a teacher and provide students mark");
			for(i=0;i<marks.size();i++)
			{
				//String name=stud_name.get(i);
				System.out.print("Enter marks ");
				float new_marks=sc.nextFloat();
		        marks.set(i, new_marks);
			}
			}	
		}
		//System.out.println(Integer.valueOf(stud_id.get(0)));
		if(marks.get(1)!=0.0)
		{
		System.out.println("If you are student then enter your id");
		int final_id=sc.nextInt();
				for(int i=0;i<stud_name.size();i++)
				{
					   if(final_id==stud_id.get(i))
					    {
						System.out.println("your name is "+stud_name.get(i));
						System.out.println("your id is "+stud_id.get(i));
						System.out.println("your age is "+stud_age.get(i));
						System.out.println("your marks is "+marks.get(i));
						break;
					    }
					continue;
				}
		}
		
		else{
			System.out.println("you are not a teacher and one more chance given to you ");
			sc.nextLine();
			System.out.println("enter your name");
			String te_name=sc.nextLine();
			for(int i=0;i<teachers.size();i++)
			{
			if(te_name.equals(teachers.get(i)) )
			{
				System.out.println("yes you are a teacher and provide students mark");
				for(i=0;i<marks.size();i++)
				{
					String name=stud_name.get(i);
					System.out.print("Enter marks for:"+name);
					float new_marks=sc.nextFloat();
			        marks.set(i, new_marks);
				}
				}	
			}
			
		}
	
	}
}
