package com.arraylist;

import java.util.Scanner;

public class student_details {
	
    public static void main(String[] args) {
    	Scanner sc=new Scanner(System.in);
    	
    	
    	System.out.println("enter how many students:");
    	int stud=sc.nextInt();
    	String batch="10th";
    	String new_name;
    	int new_id,new_age;
    	String name[]=new String[stud+1];
    	int id[]=new int[stud+1];
    	int age[]=new int[stud+1];
    	float marks[]=new float[stud+1];
    	String t_name="subasish";
    	int i,ask_id;
    	String add_name[]=new String[2];
    	int add_id[]=new int[2];
    	int add_age[]=new int[2];
    	float add_marks[]=new float[2];
    	add_name[1]="chandan";
    	
    	
    	for(i=0;i<stud;i++)
    	{
    		sc.nextLine();
    		System.out.print("Enter student name:");
    		name[i]=sc.nextLine();
    		System.out.print("Enter age:");
    		age[i]=sc.nextInt();
    		System.out.print("Enter student id:");
    		id[i]=sc.nextInt();
    	}
    	System.out.println("enter your student id we will provide your details");
    	ask_id=sc.nextInt();
    	for(i=0;i<stud;i++)
    	{
    		
    		if(ask_id==id[0] || ask_id==id[1])
    		    {
    			System.out.println("student name is:"+name[i]);
    			System.out.println("student age is:"+age[i]);
    			System.out.println("your batch is :"+batch);
    			System.out.println("your mark:"+marks[i]+" is not generated by teacher");
    			break;
    		    }
    		else {
    			System.out.println("you are new student and provide your details");
    			
    			try {
    				  //System.out.println("you are new student and provide your details");
    				 sc.nextLine(); System.out.print("your name:"); 
    				 new_name=sc.nextLine();
    				 System.out.print("your  age:"); 
    				 new_age=sc.nextInt();
    				  System.out.print("your id:"); 
    				  new_id=sc.nextInt(); 
    				  add_name[i]=new_name;
    				  add_age[i]=new_age;
    				  add_id[i]=new_id;
    				  
    				  break;
    				  } 
    			catch(Exception e) {
    				  System.out.println(e); 
    				  } 
    			
    			}	
    		}
              sc.nextLine();
           System.out.println("Enter your name if you are a teacher so that you can provide marks: ");
           System.out.println("If you entered invalid name then one more chance will given to you");
           String teach_name=sc.nextLine();
          if(teach_name.equals(t_name))
           {
    	    System.out.println("yes you are a teacher and you can provide student marks");
              for(i=0;i<stud;i++)
               {
        	      System.out.print("Enter "+name[i]+" marks:");
        	     marks[i]=sc.nextFloat();
        	     System.out.print("Enter "+add_name[i]+" marks:");
        	     add_marks[i]=sc.nextFloat();
               }
           }
        	     
          if(marks[stud-1]!=0.0)
	      {
	    	  System.out.println("if you are a student enter your id and see your marks");
	          int result_id=sc.nextInt();
	          for(i=0;i<stud;)
	          {
	        	  try {
	        	 if(id[i]==result_id ) 
	        	 {
	        		 System.out.println();
	        		 System.out.println("your name is:"+name[i]);
	     			System.out.println("your age is :"+age[i]);
	     			System.out.println("your batch is :"+batch);
	     			System.out.println("your mark:"+marks[i]);
	     			break;
	        	 }
	        	 else if(add_id[i]==result_id){
	        		 System.out.println("your name is:"+add_name[i]);
 	     			System.out.println("your age is :"+add_age[i]);
 	     			System.out.println("your batch is :"+batch);
 	     			System.out.println("your mark:"+add_marks[i]);
 	     			break;	 
	        	 }
	        	 else
	        	 {
	        		 System.out.println("you have entered wrong id & you are not allowed further to check");
	        		 break;
	        	 }
	        	  }
	        	  catch(Exception e) 
	        	  {
	        		  System.out.println();
	        	  }
	          }   
             } 
          else{
    		  System.out.println("you are not a teacher and you cant provide student marks");
    		  System.out.print("you can again enter your name:");
    		  String teacher_name=sc.nextLine();
              if(teacher_name.equals(t_name))
               {
        	    System.out.println("yes you are a teacher and you can provide student marks");
                  for(i=0;i<marks.length-1;i++)
                   {
            	      System.out.print("Enter student marks:");
            	     marks[i]=sc.nextFloat();
            	     add_marks[0]=sc.nextFloat();
            	      if(marks[stud-1]!=0.0)
            	      {
            	    	  System.out.println("Enter your id and see your marks");
            	          int result_id=sc.nextInt();
            	          for(i=0;i<stud;i++)
            	          {
            	        	 if(id[i]==result_id) 
            	        	 {
            	        		 System.out.println();
            	        		 System.out.println("your name is:"+name[i]);
            	     			System.out.println("your age is :"+age[i]);
            	     			System.out.println("your batch is :"+batch);
            	     			System.out.println("your mark:"+marks[i]);
            	     			break;
            	        	 }
            	          }
            	        }
                   }           
                 }
    		  }
          }
    }

