package com.arraylist;

import java.util.Scanner;

public class StudentManagementSystem {
	
    public static void main(String[] args) {
    	Scanner sc=new Scanner(System.in);
    	
    	
    	System.out.println("enter how many students:");
    	int stud=sc.nextInt();
    	String batch="10th";
    	String new_name;
    	int new_id,new_age;
    	String name[]=new String[stud+1];
    	int id[]=new int[stud+1];
    	int age[]=new int[stud+1];
    	float marks[]=new float[stud+1];
    	String t_name="subasish";
    	int i,ask_id;
    	
    	for(i=0;i<stud;i++)
    	{
    		sc.nextLine();
    		System.out.print("Enter student name:");
    		name[i]=sc.nextLine();
    		System.out.print("Enter age:");
    		age[i]=sc.nextInt();
    		System.out.print("Enter student id:");
    		id[i]=sc.nextInt();
    	}
    	System.out.println("enter your student id we will provide your details");
    	ask_id=sc.nextInt();
    	for(i=0;i<stud;i++)
    	{
    		
    		if(ask_id==id[0] || ask_id==id[1])
    		    {
    			System.out.println("student name is:"+name[i]);
    			System.out.println("student age is:"+age[i]);
    			System.out.println("your batch is :"+batch);
    			System.out.println("your mark:"+marks[i]+" is not generated by teacher");
    			break;
    		    }
    		else {
    			try {
    				  System.out.println("you are new student and provide your details");
    				 sc.nextLine(); System.out.print("your name:"); 
    				 new_name=sc.nextLine();
    				 System.out.print("your  age:"); 
    				 new_age=sc.nextInt();
    				  System.out.print("your id:"); 
    				  new_id=sc.nextInt(); 
    				  break;
    				  } 
    			catch(Exception e) {
    				  System.out.println(e); 
    				  } 
    			}	
    		}
              sc.nextLine();
           System.out.println("Enter your name if you are a teacher so that you can provide marks: ");
           System.out.println("If you entered invalid name then one more chance will given to you");
           String teach_name=sc.nextLine();
          if(teach_name.equals(t_name))
           {
    	    System.out.println("yes you are a teacher and you can provide student marks");
              for(i=0;i<marks.length-1;i++)
               {
        	      System.out.print("Enter student marks:");
        	     marks[i]=sc.nextFloat();
        	      if(marks[stud-1]!=0.0)
        	      {
        	    	  System.out.println("if you are a student enter your id and see your marks");
        	          int result_id=sc.nextInt();
        	          for(i=0;i<stud;i++)
        	          {
        	        	 if(id[i]==result_id) 
        	        	 {
        	        		 System.out.println();
        	        		 System.out.println("your name is:"+name[i]);
        	     			System.out.println("your age is :"+age[i]);
        	     			System.out.println("your batch is :"+batch);
        	     			System.out.println("your mark:"+marks[i]);
        	     			break;
        	        	 }
        	        	 else
        	        		 System.out.println("you have entered wrong id & you are not allowed further to check");
        	          }
        	        }
               }
        	     
              
             } 
          else{
    		  System.out.println("you are not a teacher and you cant provide student marks");
    		  System.out.print("you can again enter your name:");
    		  String teacher_name=sc.nextLine();
              if(teacher_name.equals(t_name))
               {
        	    System.out.println("yes you are a teacher and you can provide student marks");
                  for(i=0;i<marks.length-1;i++)
                   {
            	      System.out.print("Enter student marks:");
            	     marks[i]=sc.nextFloat();
            	      if(marks[stud-1]!=0.0)
            	      {
            	    	  System.out.println("Enter your id and see your marks");
            	          int result_id=sc.nextInt();
            	          for(i=0;i<stud;i++)
            	          {
            	        	 if(id[i]==result_id) 
            	        	 {
            	        		 System.out.println();
            	        		 System.out.println("your name is:"+name[i]);
            	     			System.out.println("your age is :"+age[i]);
            	     			System.out.println("your batch is :"+batch);
            	     			System.out.println("your mark:"+marks[i]);
            	     			break;
            	        	 }
            	          }
            	        }
                   }
            	     
                  
                 }
    		  }
        
          }
          
   	
    }

